apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: default
  source:
    repoURL: git@gitlab.eks.tools.icx.foundever.com:jgren008/plateform-engineering.git
    targetRevision: HEAD
    path: kyverno
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
