apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: crossplane-system
  namespace: ${ARGOCD_NAMESPACE}
spec:
  generators:
    - list:
        elements:
          - name: providers
            path: crossplane/providers
            wave: "2"
          - name: providers-config
            path: crossplane/providers-config
            wave: "3"
          - name: functions
            path: crossplane/functions
            wave: "4"
          - name: compositions
            path: crossplane/compositions/aws
            wave: "5"
          - name: xrds
            path: crossplane/xrds
            wave: "6"
          - name: claims
            path: crossplane/claims
            wave: "7"

  template:
    metadata:
      name: crossplane-{{name}}
      annotations:
        argocd.argoproj.io/sync-wave: "{{wave}}"
    spec:
      project: default
      source:
        repoURL: ${ARGOCD_REPO_URL}
        targetRevision: HEAD
        path: "{{path}}"
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: crossplane-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
